name = "toura"
type = "typescript"  # or "typescript" if you use TS

account_id = "2c34391859b0b3a6eebf4a7b4f834336"
workers_dev = true

[build]
command = "npm run build"  # or your build command

[build.upload]
dir = "dist"  # directory where your built worker script goes
main = "index.js"
